import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/layouts";
import { GlobalStyle } from "../styles";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Layout>
        <div>본 내용</div>
      </Layout>
    </div>
  );
};

export default Home;
