import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/layouts";
import { GlobalStyle, theme } from "../styles";
import { ThemeProvider } from "styled-components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Layout>
          <div>본 내용</div>
        </Layout>
      </ThemeProvider>
    </div>
  );
};

export default Home;
